# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29c833f66aae2a5c5e3c2a669f03f24d361928b5f8695ae7ff13358b64cc1870a86366f19bbd2d5fd623c36da2182dbeb82f769137a6e358a4e8a7ee0af69b0

test:
  secret_key_base: f9b154255c7b19042e52a73e6c3648b5f8433e796d97b66f16efd05f64e564a0a4cb4acc8cbed5189d2221f7ac430036eaa904264b92a819391bb5f370f17b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
